Homework 2
================
Kangkang Zhang
10/2/2018

Problem 1
---------

Load package tidyverse.

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
    ## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
    ## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
    ## ✔ readr   1.1.1     ✔ forcats 0.3.0

    ## ── Conflicts ────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

Read NYC Transit data and do data cleaning as question required.

``` r
transit_data = read_csv("./data/NYC_transit.csv") %>% 
  janitor::clean_names() %>%  
  select(line, station_name, station_latitude, station_longitude,
         starts_with("route"), entry, vending, entrance_type, ada) %>% 
   mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

This dataset is about New York transportation. It contains variables including line, station name / latitude / longitute, routes served, entry, vending, entrance\_type and ADA compliance.

Here is the data cleaning step:

1.  clean up variables'names.
2.  retain variables the question mentioned.
3.  convert the entry variable from character to logical.

The dimension of the dataset is (1868, 19).

The data are not tidy. Because some variables, such like the factor that whether a station served for A line, have values appear in different columns.

------------------------------------------------------------------------

Use distinct function to find out number of distinct stations.

``` r
distinct(transit_data, line, station_name)
```

    ## # A tibble: 465 x 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # ... with 455 more rows

There are 465 distinct stations.

------------------------------------------------------------------------

Use filter and distinct to find out number of stations which are ADA compliant.

``` r
transit_data %>% 
  filter(ada == TRUE) %>% 
  distinct(line, station_name)
```

    ## # A tibble: 84 x 2
    ##    line            station_name                  
    ##    <chr>           <chr>                         
    ##  1 4 Avenue        Atlantic Av-Barclays Ctr      
    ##  2 4 Avenue        DeKalb Av                     
    ##  3 4 Avenue        Pacific St                    
    ##  4 42nd St Shuttle Grand Central                 
    ##  5 6 Avenue        34th St                       
    ##  6 6 Avenue        47-50th Sts Rockefeller Center
    ##  7 6 Avenue        Church Av                     
    ##  8 63rd Street     21st St                       
    ##  9 63rd Street     Lexington Av                  
    ## 10 63rd Street     Roosevelt Island              
    ## # ... with 74 more rows

82 stations are ADA compliant.

------------------------------------------------------------------------

Use filter to find out proportion of station entrances / exits without vending allow entrance.

``` r
entry_data = filter(transit_data, vending == "NO" & entry == TRUE) 
dim(entry_data)[1] / dim(transit_data)[1]
```

    ## [1] 0.0369379

There are 3.69% station entrances / exits without vending allow entrance.
